version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  client:
    build:
      context: client
      dockerfile: Dockerfile

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./deployment:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - client
      - server

volumes:
  postgres_data:
